---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-argocd
  labels:
    app: gitops-argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-argocd
  template:
    metadata:
      labels:
        app: gitops-argocd
    spec:
      containers:
      - name: gitops-argocd
        image: rogerw/gitops-argocd:c3a124c145cd480f990da16ff8bca215443cbda1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gitops-service
  labels:
    app: gitops-argocd
spec:
  selector:
    app: gitops-argocd
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitops-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /gitops
        pathType: Prefix
        backend:
          service:
           name: gitops-service
           port:
            number: 80
